name: Road Runner CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:

defaults:
  run:
    working-directory: road-runner

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        validate-wrappers: true
    - name: Build with Gradle
      run: ./gradlew build

    - name: Store test reports
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: Test reports
        path: |
          **/build/reports/
          **/build/test-results/
